RUBY/FundamentosRails/libreria/config/routes.rb
Rails.application.routes.draw do
  resources :clientes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

RUBY/FundamentosRails/libreria/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

RUBY/FundamentosRails/libreria/app/models/autor.rb
class Autor < ApplicationRecord
    has_many :libros, dependent: :destroy
end

RUBY/FundamentosRails/libreria/app/models/cliente.rb
class Cliente < ApplicationRecord
end

RUBY/FundamentosRails/libreria/app/models/libro.rb
class Libro < ApplicationRecord
  belongs_to :autor
end

RUBY/FundamentosRails/libreria/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RUBY/FundamentosRails/libreria/app/controllers/clientes_controller.rb
class ClientesController < InheritedResources::Base

  private

    def cliente_params
      params.require(:cliente).permit(:nombre)
    end

end

RUBY/FundamentosRails/libreria/app/helpers/clientes_helper.rb
module ClientesHelper
end

RUBY/FundamentosRails/libreria/app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RUBY/FundamentosRails/libreria/app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

RUBY/FundamentosRails/libreria/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

RUBY/FundamentosRails/libreria/app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

RUBY/FundamentosRails/libreria/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

RUBY/FundamentosRails/libreria/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libreria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= yield %>
  </body>
</html>