RUBY/FundamentosRails/topo/config/routes.rb
Rails.application.routes.draw do
  resources :mensajes
  resources :usuarios
  resources :rols
  resources :tweets
  resources :productos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

RUBY/FundamentosRails/topo/app/models/mensaje.rb
class Mensaje < ApplicationRecord
  belongs_to :usuario
end

RUBY/FundamentosRails/topo/app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :set_mensaje, only: %i[ show edit update destroy ]

  # GET /mensajes or /mensajes.json
  def index
    @mensajes = Mensaje.all
    @usuarios = Usuario.all
  end

  # GET /mensajes/1 or /mensajes/1.json
  def show
    @usuarios = Usuario.all
  end

  # GET /mensajes/new
  def new
    @mensaje = Mensaje.new
    @usuarios = Usuario.all
  end

  # GET /mensajes/1/edit
  def edit
  end

  # POST /mensajes or /mensajes.json
  def create
    @mensaje = Mensaje.new(mensaje_params)

    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to @mensaje, notice: "Mensaje was successfully created." }
        format.json { render :show, status: :created, location: @mensaje }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensajes/1 or /mensajes/1.json
  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to @mensaje, notice: "Mensaje was successfully updated." }
        format.json { render :show, status: :ok, location: @mensaje }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1 or /mensajes/1.json
  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to mensajes_url, notice: "Mensaje was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mensaje_params
      params.require(:mensaje).permit(:content, :usuario_id)
    end
end

RUBY/FundamentosRails/topo/app/helpers/mensajes_helper.rb
module MensajesHelper
end

RUBY/FundamentosRails/topo/app/views/mensajes/_form.html.erb
<%= form_with(model: mensaje) do |form| %>
  <% if mensaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mensaje.errors.count, "error") %> prohibited this mensaje from being saved:</h2>

      <ul>
        <% mensaje.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= collection_select(:mensaje, :usuario_id, Usuario.all, :id, :nombre, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RUBY/FundamentosRails/topo/app/views/mensajes/edit.html.erb
<h1>Editing Mensaje</h1>

<%= render 'form', mensaje: @mensaje %>

<%= link_to 'Show', @mensaje %> |
<%= link_to 'Back', mensajes_path %>

RUBY/FundamentosRails/topo/app/views/mensajes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mensajes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr>
        <td><%= mensaje.content %></td>

        <td>
        <% @usuarios.each do |usuario| %>
          <% if usuario.id == mensaje.usuario_id %>
            <%= usuario.nombre %>
          <% end %>
        <% end %>
      </td>


        <td><%= link_to 'Show', mensaje %></td>
        <td><%= link_to 'Edit', edit_mensaje_path(mensaje) %></td>
        <td><%= link_to 'Destroy', mensaje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mensaje', new_mensaje_path %>

RUBY/FundamentosRails/topo/app/views/mensajes/new.html.erb
<h1>New Mensaje</h1>

<%= render 'form', mensaje: @mensaje %>

<%= link_to 'Back', mensajes_path %>

RUBY/FundamentosRails/topo/app/views/mensajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @mensaje.content %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @mensaje.usuario_id %>
</p>

<%= link_to 'Edit', edit_mensaje_path(@mensaje) %> |
<%= link_to 'Back', mensajes_path %>