RUBY/FundamentosRails/topo/config/routes.rb
Rails.application.routes.draw do
  resources :mensajes
  resources :usuarios
  resources :rols
  resources :tweets
  resources :productos
  resources :clientes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

RUBY/FundamentosRails/topo/app/models/rol.rb
class Rol < ApplicationRecord
end

RUBY/FundamentosRails/topo/app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: %i[ show edit update destroy ]

  # GET /rols or /rols.json
  def index
    @rols = Rol.all
    @usuarios = Usuario.all
  end

  # GET /rols/1 or /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols or /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: "Rol was successfully created." }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1 or /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: "Rol was successfully updated." }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1 or /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: "Rol was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rol_params
      params.require(:rol).permit(:nombre)
    end
end

RUBY/FundamentosRails/topo/app/helpers/rols_helper.rb
module RolsHelper
end

RUBY/FundamentosRails/topo/app/views/rols/_form.html.erb
<%= form_with(model: rol) do |form| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
        <% rol.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RUBY/FundamentosRails/topo/app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

RUBY/FundamentosRails/topo/app/views/rols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.nombre %></td>
        <td><%= link_to 'Show', rol %></td>
        <td><%= link_to 'Edit', edit_rol_path(rol) %></td>
        <td><%= link_to 'Destroy', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Rol', new_rol_path %>

RUBY/FundamentosRails/topo/app/views/rols/new.html.erb
<h1>New Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

RUBY/FundamentosRails/topo/app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rol.nombre %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>